modelEncoding: UTF-8
modelVersion: 4.0.0
groupId: com.github.stcarolas.enki
artifactId: enki-jacoco-configurator
version: 0.1.29
packaging: jar
name: Enki Jacoco Configurator
properties: {revision: 0.0.1, java.version: 1.8, maven.compiler.source: 1.8, maven.compiler.target: 1.8}
dependencies:
- {groupId: com.github.stcarolas.enki, artifactId: enki-core, version: '${project.version}'}
- {groupId: org.apache.logging.log4j, artifactId: log4j-api, version: 2.12.1}
- {groupId: org.apache.logging.log4j, artifactId: log4j-core, version: 2.12.1}
- {groupId: org.yaml, artifactId: snakeyaml, version: 1.25}
- {groupId: io.undertow, artifactId: undertow-core, version: 2.0.1.Final}
- {groupId: io.vavr, artifactId: vavr, version: 1.0.0-alpha-3}
- {groupId: com.github.stcarolas.gittemplateloader, artifactId: handlebars-git-templateloader,
  version: 0.0.1}
- {groupId: org.projectlombok, artifactId: lombok, version: 1.18.8, scope: provided,
  optional: true}
- {groupId: info.picocli, artifactId: picocli, version: 4.0.3}
- {groupId: io.projectreactor, artifactId: reactor-core, version: 3.2.12.RELEASE}
- {groupId: com.google.code.gson, artifactId: gson, version: 2.8.5}
build:
  plugins:
  - {groupId: org.apache.maven.plugins, artifactId: maven-surefire-plugin}
  - groupId: org.apache.maven.plugins
    artifactId: maven-compiler-plugin
    configuration:
      annotationProcessorPaths:
      - {groupId: org.projectlombok, artifactId: lombok, version: 1.18.8}
  - groupId: org.apache.maven.plugins
    artifactId: maven-shade-plugin
    version: 3.2.1
    executions:
    - configuration:
        transformers:
          org.apache.maven.plugins.shade.resource.ManifestResourceTransformer: {mainClass: com.github.stcarolas.enki.Application}
        filters:
        - artifact: '*:*'
          excludes: [META-INF/*.SF, META-INF/*.DSA, META-INF/*.RSA]
      goals: [shade]
      id: shade
      inherited: true
      phase: package
      priority: 0
  - groupId: org.jacoco
    artifactId: jacoco-maven-plugin
    version: 0.8.4
    executions:
    - goals: [prepare-agent]
      id: default-prepare-agent
      inherited: true
      priority: 0
    - goals: [report]
      id: default-report
      inherited: true
      phase: prepare-package
      priority: 0
    - goals: [report]
      id: default-check
      inherited: true
      phase: test
      priority: 0
repositories:
- {id: enki-github-repo, layout: default, url: 'https://maven.pkg.github.com/stCarolas/Enki'}
