modelEncoding: UTF-8
modelVersion: 4.0.0
groupId: com.github.stcarolas.enki
artifactId: enki-logging-handlers
version: 0.1.34
packaging: jar
name: Enki Logging Analyzers
properties: {revision: 0.0.1, java.version: 1.8, maven.compiler.source: 1.8, maven.compiler.target: 1.8}
dependencies:
- {groupId: com.github.stcarolas.enki, artifactId: enki-core, version: '${project.version}'}
- {groupId: org.apache.logging.log4j, artifactId: log4j-api, version: 2.12.1}
- {groupId: org.apache.logging.log4j, artifactId: log4j-core, version: 2.12.1}
- {groupId: org.projectlombok, artifactId: lombok, version: 1.18.8, scope: provided,
  optional: true}
distributionManagement:
  repository: {id: github, layout: default, name: github, uniqueVersion: false, url: 'https://maven.pkg.github.com/stCarolas/Enki'}
build:
  plugins:
  - {groupId: org.apache.maven.plugins, artifactId: maven-surefire-plugin}
  - groupId: org.apache.maven.plugins
    artifactId: maven-compiler-plugin
    configuration:
      annotationProcessorPaths:
      - {groupId: org.projectlombok, artifactId: lombok, version: 1.18.8}
repositories:
- {id: enki-github-repo, layout: default, url: 'https://maven.pkg.github.com/stCarolas/Enki'}
- {id: jcenter, layout: default, name: jcenter, url: 'https://jcenter.bintray.com'}
